name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true

    - name: Scan for common Rails security vulnerabilities using static analysis
      run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true

    - name: Lint code for consistent style
      run: bin/rubocop -f github

  test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git pkg-config

    - name: Set up SQLite database
      run: |
        cp config/database.yml.ci config/database.yml
        bin/rails db:create db:migrate

    - name: Run tests
      env:
        RAILS_ENV: test
      run: bin/rails test
